stages:
  - vault
  - tf

vault:
  artifacts:
    expire_in: 5 mins
    paths:
    - serviceaccount.json
  stage: vault
  image: vault
  script:
  - export VAULT_ADDR=https://vault.*****.***
  - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=app2020 jwt=$CI_JOB_JWT)"
  - export SVC_ACCOUNT="$(vault kv get -field=serviceaccount1 path/serviceaccount)"
  - echo "$SVC_ACCOUNT" | base64 -d > serviceaccount.json


tf:
  artifacts:
    expire_in: 5 mins
    paths:
    - serviceaccount.json
  stage: tf
  image:
    name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
  - terraform init
  - terraform plan
  - terraform apply --auto-approve
